import {initial,events,ranked,applyEvent,nearby,visibleLineup} from '../live-ranking/model.mjs';
const $=id=>document.getElementById(id);
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const fmt=n=>(n/10).toFixed(1);
let users=structuredClone(initial),step=0,near=false,playing=false,timer=null,busy=false,releaseTimer=null,toastTimer=null,selected='me',focusedPlayer='tatum',version=0;
const cards=new Map();
const slots=['PG','SG','SF','PF','C'];
const courtPositions={PG:[30,75],SG:[77,65],SF:[20,42],PF:[74,32],C:[49,24]};
function navigate(view,scroll=true){
 if(!['home','lineup','rankings','intel'].includes(view))view='home';
 document.querySelectorAll('[data-view]').forEach(el=>el.hidden=el.dataset.view!==view);
 document.querySelectorAll('.topbar [data-nav]').forEach(el=>{el.classList.toggle('active',el.dataset.nav===view);if(el.dataset.nav===view)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current')});
 document.body.classList.toggle('ranking-active',view==='rankings');document.querySelector('.control-dock').hidden=view!=='rankings';
 if(view!=='rankings')stop();if(scroll)window.scrollTo({top:0,behavior:'instant'});
}
document.querySelectorAll('[data-nav]').forEach(el=>el.addEventListener('click',()=>navigate(el.dataset.nav)));
window.addEventListener('hashchange',()=>navigate(location.hash.slice(1)));
$('hero-play').onclick=()=>{history.pushState(null,'','#rankings');navigate('rankings');start()};
function numeric(node,value,animate){const from=Number(node.textContent)||0,to=value/10,v=version;if(!animate||reduced.matches){node.textContent=to.toFixed(1);return}const start=performance.now();function frame(now){if(v!==version)return;const t=Math.min(1,(now-start)/650);node.textContent=(from+(to-from)*(1-(1-t)**3)).toFixed(1);if(t<1)requestAnimationFrame(frame)}requestAnimationFrame(frame)}
function makeCard(user){
 const card=document.createElement('article');card.dataset.id=user.id;card.innerHTML='<details><summary><span class="rank"><b></b><small></small></span><span class="monogram"></span><span class="identity"><strong></strong><small></small></span><span class="score"><b>0.0</b><small></small></span></summary><div class="runner-details"></div></details>';
 card.querySelector('.monogram').textContent=user.mark;card.querySelector('.identity strong').textContent=user.name;if(user.id==='me'){const tag=document.createElement('em');tag.textContent='YOU';card.querySelector('.identity strong').append(tag)}
 card.querySelector('details').addEventListener('toggle',e=>{card.querySelector('summary').setAttribute('aria-label',`${user.name}，${e.target.open?'收起':'查看'}已开赛阵容`);if(e.target.open){selected=user.id;renderCourt();markSelected()}});
 card.querySelector('summary').addEventListener('click',()=>{selected=user.id;renderCourt();markSelected()});return card;
}
function markSelected(){for(const[id,card]of cards)card.classList.toggle('selected',id===selected)}
function playerList(players){const list=document.createElement('ul');list.className='player-list';for(const player of players){const li=document.createElement('li'),position=document.createElement('span'),identity=document.createElement('span'),name=document.createElement('strong'),status=document.createElement('small'),score=document.createElement('b');position.textContent=player.position;name.textContent=player.name;status.textContent=player.status==='live'?'比赛中':'已完赛';score.textContent=fmt(player.score);identity.append(name,status);li.append(position,identity,score);list.append(li)}return list}
function render(event=null,previous=[]){
 version++;const standings=ranked(users),me=standings.find(u=>u.id==='me'),index=standings.findIndex(u=>u.id==='me');
 const positions=new Map([...cards].filter(([,card])=>card.isConnected).map(([id,card])=>[id,card.getBoundingClientRect().top]));
 for(const user of standings){if(!cards.has(user.id))cards.set(user.id,makeCard(user));const card=cards.get(user.id),old=previous.find(p=>p.id===user.id),move=old?old.rank-user.rank:0;
 card.className=`runner${user.id==='me'?' mine':''}${user.rank===1?' leader':''}${user.id===selected?' selected':''}`;card.querySelector('.rank>b').textContent=String(user.rank).padStart(2,'0');card.querySelector('.rank>small').textContent=move>0?'↑ '+move:move<0?'↓ '+Math.abs(move):user.rank===1?'LEADER':'';
 card.querySelector('.identity>small').textContent=user.live?`${user.live} 人比赛中${user.waiting?' · '+user.waiting+' 人待赛':''}`:user.waiting?`${user.waiting} 人待赛`:'全部完赛';numeric(card.querySelector('.score>b'),user.score,event?.id===user.id);const note=card.querySelector('.score>small');note.textContent=event?.id===user.id?'+'+fmt(event.points)+' FP':'查看详情';note.className=event?.id===user.id?'gain':'';
 const details=card.querySelector('.runner-details'),players=visibleLineup(user),intro=document.createElement('p');intro.textContent=`已开赛 ${players.length} / 5 人 · 未开赛球员暂不公开`;details.replaceChildren(intro,playerList(players));card.querySelector('summary').setAttribute('aria-label',`${user.name}，${card.querySelector('details').open?'收起':'查看'}已开赛阵容`);
 }
 const visible=near?nearby(standings,'me'):standings;
 for(const[id,card]of cards)if(!visible.some(u=>u.id===id))card.remove();
 for(const user of visible)$('race').append(cards.get(user.id));
 if(event&&!reduced.matches)for(const user of visible){const card=cards.get(user.id),old=positions.get(user.id);if(old!==undefined){const dy=old-card.getBoundingClientRect().top;if(Math.abs(dy)>1)card.animate([{transform:`translateY(${dy}px)`},{transform:'translateY(0)'}],{duration:700,easing:'cubic-bezier(.16,1,.3,1)'});}}
 $('my-rank').textContent=String(me.rank).padStart(2,'0');numeric($('my-score'),me.score,event?.id==='me');$('gap-label').textContent=index===0?'领先下一名':'距离上一名';$('gap').textContent=fmt(index===0?me.score-standings[1].score:standings[index-1].score-me.score);
 const before=previous.find(u=>u.id==='me'),delta=before?before.rank-me.rank:0;$('my-move').textContent=delta>0?`UP ${delta} PLACE${delta>1?'S':''}`:delta<0?'STAY IN THE GAME':me.rank===1?'KING OF THE COURT':'READY TO RISE';$('my-message').textContent=me.rank===1?'现在，这里是你的主场。':delta>0?'反超。别停，继续往上。':delta<0?'被反超了，下个回合打回来。':'下一回合，把名次打上去。';
 $('all').setAttribute('aria-pressed',String(!near));$('near').setAttribute('aria-pressed',String(near));$('next').disabled=busy||step===events.length;$('play').disabled=step===events.length;$('step-label').textContent=step?`${step} / 7 回合${step===7?' · 已完成':' · 逆转进行中'}`:'7 个回合，见证逆转';$('timeline').replaceChildren(...events.map((_,i)=>{const item=document.createElement('span');item.className=i<step?'done'+(i===step-1?' current':''):'';return item}));renderCourt();
}
function renderCourt(){const user=users.find(u=>u.id===selected),players=visibleLineup(user);$('roster-owner').textContent=user.name+'的主场';$('roster-count').textContent=players.length+' / 5';if(!players.some(p=>p.id===focusedPlayer))focusedPlayer=players[0]?.id;
 $('court-players').replaceChildren(...players.map(player=>{const button=document.createElement('button');button.className='court-player';const[x,y]=courtPositions[player.position];button.style.setProperty('--x',x+'%');button.style.setProperty('--y',y+'%');button.setAttribute('aria-label',player.position+' '+player.name+'，'+fmt(player.score)+' 梦幻分');button.setAttribute('aria-pressed',String(focusedPlayer===player.id));const pos=document.createElement('b'),name=document.createElement('span');pos.textContent=player.position;name.textContent=player.name.split('·').at(-1);button.append(pos,name);button.onclick=()=>{focusedPlayer=player.id;renderCourt()};return button}));
 const focus=players.find(p=>p.id===focusedPlayer);if(focus){const copy=document.createElement('span'),name=document.createElement('strong'),status=document.createElement('small'),score=document.createElement('b');name.textContent=focus.name;status.textContent=focus.position+' / '+(focus.status==='live'?'比赛中':'已完赛');score.textContent=fmt(focus.score);copy.append(name,status);$('player-focus').replaceChildren(copy,score)}else $('player-focus').textContent='尚无球员开赛。';
}
function toast(score,title,copy){clearTimeout(toastTimer);$('toast-score').textContent=score;$('toast-title').textContent=title;$('toast-copy').textContent=copy;const node=$('score-toast');node.classList.remove('show');void node.offsetWidth;node.classList.add('show');toastTimer=setTimeout(()=>node.classList.remove('show'),2500)}
function stop(){playing=false;clearInterval(timer);timer=null;$('play').textContent='自动演示';$('play').setAttribute('aria-pressed','false');$('play-dot').classList.remove('playing');$('play-label').textContent=step===7?'终场。主场属于你。':'比赛，由你推进。'}
function next(){if(busy||step>=events.length)return;busy=true;const before=ranked(users),event=events[step++];users=applyEvent(users,event);const user=ranked(users).find(u=>u.id===event.id),old=before.find(u=>u.id===event.id);selected=user.id;focusedPlayer=user.featuredId;
 const message=`${user.name} +${fmt(event.points)} 分，${user.rank<old.rank?'反超至':'目前'}第 ${user.rank} 名。`;$('announcement').textContent=message;$('event-count').textContent='ROUND '+String(step).padStart(2,'0');const li=document.createElement('li'),number=document.createElement('span'),copy=document.createElement('div'),heading=document.createElement('strong'),detail=document.createElement('small');number.textContent=String(step).padStart(2,'0');heading.textContent=user.player+' · '+event.action;detail.textContent=message;copy.append(heading,detail);li.append(number,copy);$('feed').prepend(li);
 render(event,before);toast('+'+fmt(event.points),user.rank===1?'KING OF THE COURT':user.rank<old.rank?'TAKEOVER':'BUCKETS',message);$('shot-line').classList.remove('shoot');void $('shot-line').offsetWidth;$('shot-line').classList.add('shoot');if(step===7)stop();releaseTimer=setTimeout(()=>{busy=false;$('next').disabled=step===7},800);
}
function start(){if(playing){stop();return}if(step===7)return;playing=true;$('play').textContent='暂停演示';$('play').setAttribute('aria-pressed','true');$('play-label').textContent='主场升温中。';$('play-dot').classList.add('playing');timer=setInterval(next,4200);next()}
$('next').onclick=next;$('play').onclick=start;$('reset').onclick=()=>{stop();clearTimeout(releaseTimer);clearTimeout(toastTimer);$('score-toast').classList.remove('show');step=0;busy=false;users=structuredClone(initial);selected='me';focusedPlayer='tatum';near=false;for(const card of cards.values()){card.getAnimations().forEach(a=>a.cancel());card.querySelector('details').open=false}$('feed').replaceChildren();$('announcement').textContent='塔图姆准备出手。水哥距第 3 名，只差 2.2 分。';$('event-count').textContent='WAITING';$('play-label').textContent='比赛，由你推进。';render()};
$('all').onclick=()=>{near=false;render()};$('near').onclick=()=>{near=true;render()};$('locate').onclick=()=>{history.pushState(null,'','#rankings');navigate('rankings',false);const card=cards.get('me');card.scrollIntoView({block:'center',behavior:reduced.matches?'instant':'smooth'});card.querySelector('summary').focus({preventScroll:true})};
$('court-stage').addEventListener('pointermove',e=>{if(reduced.matches||e.pointerType!=='mouse')return;const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--tilt-x',((e.clientY-r.top)/r.height-.5)*-7+'deg');e.currentTarget.style.setProperty('--tilt-y',((e.clientX-r.left)/r.width-.5)*9+'deg')});$('court-stage').addEventListener('pointerleave',e=>{e.currentTarget.style.setProperty('--tilt-x','0deg');e.currentTarget.style.setProperty('--tilt-y','0deg')});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});
// The team builder uses a separate, local-only draft. No production requests.
const pool=[{id:'curry',name:'斯蒂芬·库里',en:'Stephen Curry',position:'PG',team:'GSW',salary:30,fp:39.2,number:30},{id:'brunson',name:'杰伦·布伦森',en:'Jalen Brunson',position:'PG',team:'NYK',salary:24,fp:34.8,number:11},{id:'booker',name:'德文·布克',en:'Devin Booker',position:'SG',team:'PHX',salary:25,fp:35.6,number:1},{id:'mitchell',name:'多诺万·米切尔',en:'Donovan Mitchell',position:'SG',team:'CLE',salary:27,fp:37.1,number:45},{id:'tatum',name:'杰森·塔图姆',en:'Jayson Tatum',position:'SF',team:'BOS',salary:28,fp:42.6,number:0},{id:'durant',name:'凯文·杜兰特',en:'Kevin Durant',position:'SF',team:'PHX',salary:30,fp:40.8,number:35},{id:'giannis',name:'扬尼斯·阿德托昆博',en:'Giannis Antetokounmpo',position:'PF',team:'MIL',salary:35,fp:48.2,number:34},{id:'davis',name:'安东尼·戴维斯',en:'Anthony Davis',position:'PF',team:'LAL',salary:24,fp:38.2,number:3},{id:'jokic',name:'尼古拉·约基奇',en:'Nikola Jokic',position:'C',team:'DEN',salary:38,fp:51.2,number:15},{id:'sengun',name:'阿尔佩伦·申京',en:'Alperen Sengun',position:'C',team:'HOU',salary:18,fp:28.4,number:28}];
let picks={},filter='ALL',saved=null;
const salary=()=>Object.values(picks).reduce((sum,p)=>sum+p.salary,0);
function pick(player){const nextCost=salary()-(picks[player.position]?.salary??0)+player.salary;if(nextCost>125){$('builder-message').textContent=`预算还差 $${nextCost-125}，先替换一位球员试试。`;toast('$'+(nextCost-125),'OVER BUDGET','总薪资不能超过 $125');return}picks[player.position]=player;$('builder-message').textContent=player.name+' 已上场。';renderBuilder()}
function renderBuilder(){const cost=salary(),count=Object.keys(picks).length;$('budget-left').textContent='$'+(125-cost);$('picked-count').textContent=count+' / 5';$('budget-bar').style.width=cost/125*100+'%';$('save-lineup').disabled=count!==5||cost>125;
 $('slot-targets').replaceChildren(...slots.map(slot=>{const button=document.createElement('button'),player=picks[slot];button.className='slot-target'+(player?' chosen':'');button.dataset.slot=slot;const[x,y]=courtPositions[slot];button.style.setProperty('--x',x+'%');button.style.setProperty('--y',y+'%');button.setAttribute('aria-label',slot+(player?' '+player.name+'，点击移除':'，选择球员'));const position=document.createElement('b'),name=document.createElement('strong'),price=document.createElement('small');position.textContent=slot;name.textContent=player?player.name.split('·').at(-1):'选择球员';price.textContent=player?'$'+player.salary:'拖拽到这里';button.append(position,name,price);button.onclick=()=>{if(player){delete picks[slot];$('builder-message').textContent=player.name+' 已移出阵容。';renderBuilder()}else{filter=slot;renderBuilder();$('player-search').focus({preventScroll:true})}};
 button.ondragover=e=>{e.preventDefault();button.classList.add('drag-over')};button.ondragleave=()=>button.classList.remove('drag-over');button.ondrop=e=>{e.preventDefault();button.classList.remove('drag-over');const player=pool.find(p=>p.id===e.dataTransfer.getData('text/plain'));if(!player)return;if(player.position!==slot){$('builder-message').textContent=`${player.name} 需要放在 ${player.position} 位置。`;return}pick(player)};return button}));
 $('position-filters').replaceChildren(...['ALL',...slots].map(position=>{const button=document.createElement('button');button.textContent=position;button.setAttribute('aria-pressed',String(filter===position));button.onclick=()=>{filter=position;renderBuilder()};return button}));
 const query=$('player-search').value.trim().toLowerCase(),visible=pool.filter(p=>(filter==='ALL'||p.position===filter)&&(!query||(p.name+' '+p.en).toLowerCase().includes(query)));
 $('pool-list').replaceChildren(...visible.map(player=>{const button=document.createElement('button'),chosen=picks[player.position]?.id===player.id;button.className='pool-player'+(chosen?' selected':'');button.draggable=false;button.setAttribute('aria-label',player.name+'，'+player.position+'，$'+player.salary+(chosen?'，已选入':'，选入阵容'));const number=document.createElement('span'),copy=document.createElement('span'),name=document.createElement('strong'),meta=document.createElement('small'),price=document.createElement('b');number.textContent=String(player.number).padStart(2,'0');name.textContent=player.name;meta.textContent=player.team+' / '+player.position+' · FP '+player.fp.toFixed(1);price.textContent=chosen?'已上场':'$'+player.salary;copy.append(name,meta);button.append(number,copy,price);button.onclick=()=>{if(!dragSuppressed)pick(player)};button.onpointerdown=e=>beginDrag(e,player,button);return button}));if(!visible.length){const empty=document.createElement('p');empty.className='pool-empty';empty.textContent='没有找到球员，换个名字或位置试试。';$('pool-list').append(empty)}
}
function showSaved(show){$('builder').hidden=show;$('saved-view').hidden=!show;$('edit-tab').setAttribute('aria-pressed',String(!show));$('saved-tab').setAttribute('aria-pressed',String(show));if(!show)return;const section=document.createElement('div');if(!saved){section.className='saved-empty';section.innerHTML='<h2>你的主场，还差五个人。</h2><p>保存一份阵容后，就能在这里找到它。</p>';const button=document.createElement('button');button.className='orange-button';button.textContent='开始组队';button.onclick=()=>showSaved(false);section.append(button)}else{section.className='saved-lineup';section.innerHTML='<header><h2>水哥的主场阵容</h2><span>已保存 · 仅本次演示</span></header>';const list=document.createElement('ul');list.className='player-list';for(const slot of slots){const player=saved[slot],li=document.createElement('li');li.innerHTML='<span></span><strong></strong><b></b>';li.children[0].textContent=slot;li.children[1].textContent=player.name;li.children[2].textContent='$'+player.salary;list.append(li)}const cost=document.createElement('p');cost.textContent='总薪资 $'+Object.values(saved).reduce((s,p)=>s+p.salary,0)+' / $125';const actions=document.createElement('div'),edit=document.createElement('button'),remove=document.createElement('button');edit.className='orange-button';edit.textContent='编辑阵容';edit.onclick=()=>{picks=structuredClone(saved);renderBuilder();showSaved(false)};remove.className='text-button';remove.textContent='删除演示阵容';remove.onclick=()=>{saved=null;$('saved-count').textContent='0';showSaved(true)};actions.append(edit,remove);section.append(list,cost,actions)}$('saved-content').replaceChildren(section)}
$('player-search').oninput=renderBuilder;$('preset').onclick=()=>{picks=Object.fromEntries(['curry','booker','tatum','davis','sengun'].map(id=>{const p=pool.find(p=>p.id===id);return[p.position,p]}));filter='ALL';$('builder-message').textContent='五人就位，刚好用满 $125。';renderBuilder()};$('save-lineup').onclick=()=>{if(Object.keys(picks).length!==5||salary()>125)return;saved=structuredClone(picks);$('saved-count').textContent='1';toast('05','SQUAD LOCKED','演示阵容已保存，刷新页面后重置。');showSaved(true)};$('edit-tab').onclick=()=>showSaved(false);$('saved-tab').onclick=()=>showSaved(true);
document.querySelectorAll('[data-intel]').forEach(button=>button.onclick=()=>{const tab=button.dataset.intel;$('intel-players').hidden=tab!=='players';$('intel-starters').hidden=tab!=='starters';document.querySelectorAll('[data-intel]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)))});
const roles=[['杰森·塔图姆',6.4,72,86],['杰伦·布伦森',4.2,58,74],['阿尔佩伦·申京',3.8,48,63]];
for(const[name,change,before,after]of roles){const row=document.createElement('div');row.className='role-row';row.innerHTML='<div><strong></strong><b></b></div><div class="role-bars"><span></span><span></span></div><small>灰色：前 10 场 / 橙色：近 5 场 · 模拟梦幻分</small>';row.querySelector('strong').textContent=name;row.querySelector('b').textContent='+'+change.toFixed(1);row.querySelectorAll('.role-bars span').forEach((el,i)=>el.style.setProperty('--bar',(i?after:before)+'%'));$('role-list').append(row)}
const starterSets=[[['BOS',['朱·霍勒迪','德里克·怀特','杰森·塔图姆','杰伦·布朗','克里斯塔普斯·波尔津吉斯']],['NYK',['杰伦·布伦森','米卡尔·布里奇斯','OG·阿奴诺比','乔什·哈特','卡尔·安东尼·唐斯']]],[['GSW',['斯蒂芬·库里','布兰丁·波杰姆斯基','摩西·穆迪','德雷蒙德·格林','特雷斯·杰克逊-戴维斯']],['LAL',['卢卡·东契奇','奥斯汀·里夫斯','勒布朗·詹姆斯','八村垒','贾克森·海斯']]]];
function renderStarters(index){$('starter-teams').className='starter-teams';$('starter-teams').replaceChildren(...starterSets[index].map(([team,names])=>{const section=document.createElement('section');section.className='starter-team';const header=document.createElement('header'),title=document.createElement('h3'),status=document.createElement('span'),list=document.createElement('ul');title.textContent=team;status.textContent='模拟预测 · 未确认';header.append(title,status);names.forEach((name,i)=>{const li=document.createElement('li'),slot=document.createElement('span');slot.textContent=slots[i];li.append(slot,document.createTextNode(name));list.append(li)});section.append(header,list);return section}))}
document.querySelectorAll('[data-starter]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-starter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));renderStarters(Number(button.dataset.starter))});
const matchComments=['最后两分钟，每一个回合都可能改写排名。塔图姆带队守住 2 分优势。','第三节，比赛还在拉锯。库里用一记三分，把场边的气氛点燃。','双方尚未开赛。已选球员的身份将保留隐藏，开赛后再亮相。'];
document.querySelectorAll('[data-match]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-match]').forEach(b=>b.classList.toggle('active',b===button));$('match-comment').textContent=matchComments[Number(button.dataset.match)]});
render();renderBuilder();renderStarters(0);navigate(location.hash.slice(1)||'home',false);


let dragging=null,dragSuppressed=false;
function beginDrag(event,player,button){
 if(event.pointerType!=='mouse'||event.button!==0)return;
 dragSuppressed=false;dragging={player,x:event.clientX,y:event.clientY,active:false,node:null};button.setPointerCapture(event.pointerId);
 button.onpointermove=e=>{if(!dragging)return;if(!dragging.active&&Math.hypot(e.clientX-dragging.x,e.clientY-dragging.y)>7){dragging.active=true;dragging.node=document.createElement('div');dragging.node.className='drag-preview';dragging.node.textContent=player.position+' / '+player.name;document.body.append(dragging.node)}if(!dragging.active)return;dragging.node.style.left=e.clientX+15+'px';dragging.node.style.top=e.clientY+15+'px';document.querySelectorAll('.slot-target').forEach(el=>el.classList.remove('drag-over'));document.elementFromPoint(e.clientX,e.clientY)?.closest('.slot-target')?.classList.add('drag-over')};
 button.onpointerup=e=>{if(!dragging)return;const state=dragging;dragging=null;state.node?.remove();document.querySelectorAll('.slot-target').forEach(el=>el.classList.remove('drag-over'));if(!state.active)return;dragSuppressed=true;const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.slot-target');if(target){if(target.dataset.slot===player.position)pick(player);else $('builder-message').textContent=player.name+' 需要放在 '+player.position+' 位置。'}setTimeout(()=>dragSuppressed=false,0)};
 button.onpointercancel=()=>{dragging?.node?.remove();dragging=null;document.querySelectorAll('.slot-target').forEach(el=>el.classList.remove('drag-over'))};
}

// Local player search updates the existing scouting report. No production requests.
const scoutMetrics={curry:[4.1,33.8],brunson:[4.2,35.1],booker:[2.6,34.6],mitchell:[3.1,33.2],tatum:[6.4,34.2],durant:[1.8,35.5],giannis:[5.2,34.8],davis:[2.7,33.6],jokic:[4.8,35.2],sengun:[3.8,31.4]};
function createScoutSearch(index){
 const section=document.createElement('section');section.className='intel-search-column';section.setAttribute('aria-label','球员搜索与情报');
 const label=document.createElement('label');label.className='intel-search-label';label.htmlFor='scout-search-'+index;label.textContent='搜索球员';
 const field=document.createElement('div');field.className='intel-search-field';field.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/></svg>';
 const input=document.createElement('input');input.type='search';input.id=label.htmlFor;input.placeholder='输入中文或英文姓名';input.autocomplete='off';input.setAttribute('aria-controls','scout-results-'+index);
 const clear=document.createElement('button');clear.className='intel-clear';clear.textContent='清空';clear.setAttribute('aria-label','清空球员搜索');clear.disabled=true;
 const results=document.createElement('div');results.className='intel-search-results';results.id='scout-results-'+index;results.hidden=true;results.setAttribute('aria-label','球员 '+index+' 搜索结果');
 const report=document.createElement('div');report.className='intel-search-report';
 const status=document.createElement('p');status.className='intel-search-status';status.setAttribute('role','status');
 let selectedPlayer=null,matches=[];
 const empty=()=>{report.replaceChildren();const title=document.createElement('h3'),hint=document.createElement('p');title.textContent='谁值得上场？';hint.textContent='搜索并选择一位球员，查看梦幻分、角色变化与出场时间。';report.classList.add('empty');report.append(title,hint)};
 function select(player){
  selectedPlayer=player;input.value=player.name;clear.disabled=false;results.hidden=true;report.classList.remove('empty');report.replaceChildren();
  const [change,minutes]=scoutMetrics[player.id];
  const feature=document.createElement('section');feature.className='scout-feature';
  const copy=document.createElement('div');copy.className='scout-copy';
  const team=document.createElement('span');team.className='scout-team';team.textContent=player.team+' / '+player.position;
  const heading=document.createElement('h2'),surname=document.createElement('span');const parts=player.en.toUpperCase().split(' ');surname.textContent=parts.pop()+'.';heading.append(document.createTextNode(parts.join(' ')),document.createElement('br'),surname);
  const name=document.createElement('p');name.textContent=player.name;
  const add=document.createElement('button');add.className='orange-button';add.textContent='加入我的阵容';add.setAttribute('aria-label','将'+player.name+'加入我的阵容');add.onclick=()=>{history.pushState(null,'','#lineup');navigate('lineup');showSaved(false);pick(player)};
  copy.append(team,heading,name,add);
  const number=document.createElement('div');number.className='scout-number';number.setAttribute('aria-hidden','true');number.textContent=player.number;
  const stats=document.createElement('div');stats.className='scout-stats';for(const [value,label]of [[player.fp.toFixed(1),'模拟近 5 场梦幻分'],['+'+change.toFixed(1),'较前 10 场提升'],[minutes.toFixed(1),'场均出场分钟']]){const row=document.createElement('div'),valueEl=document.createElement('b'),labelEl=document.createElement('span');valueEl.textContent=value;labelEl.textContent=label;row.append(valueEl,labelEl);stats.append(row)}
  feature.append(copy,number,stats);report.append(feature);status.textContent='当前显示：'+player.name+' · 演示数据';input.focus({preventScroll:true});
 }
 function search(){const query=input.value.trim().toLowerCase();clear.disabled=!input.value;selectedPlayer=null;empty();results.replaceChildren();if(!query){results.hidden=true;status.textContent='';matches=[];return}matches=pool.filter(p=>(p.name+' '+p.en).toLowerCase().includes(query));results.hidden=false;if(!matches.length){const message=document.createElement('p');message.className='intel-no-results';message.textContent='未找到球员，试试其他姓名。';results.append(message)}else{for(const player of matches){const button=document.createElement('button');button.className='intel-result';const name=document.createElement('strong'),meta=document.createElement('small');name.textContent=player.name;meta.textContent=player.en+' · '+player.position;button.append(name,meta);button.onclick=()=>select(player);results.append(button)}}status.textContent=matches.length?'找到 '+matches.length+' 位球员，点击姓名查看。':'没有匹配结果。';}
 input.oninput=search;input.onkeydown=event=>{if(event.key==='Escape'){results.hidden=true;return}if(event.key==='ArrowDown'&&!results.hidden){event.preventDefault();results.querySelector('button')?.focus()}if(event.key==='Enter'&&!results.hidden&&matches.length){event.preventDefault();select(matches[0])}};
 results.onkeydown=event=>{const buttons=[...results.querySelectorAll('button')],active=buttons.indexOf(document.activeElement);if(event.key==='Escape'){results.hidden=true;input.focus();return}if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();const next=active+(event.key==='ArrowDown'?1:-1);if(next<0)input.focus();else buttons[Math.min(next,buttons.length-1)]?.focus()}};
 clear.onclick=()=>{input.value='';search();input.focus()};
 input.onfocus=()=>{if(!selectedPlayer&&input.value)results.hidden=false};
 section.addEventListener('focusout',()=>{setTimeout(()=>{if(!section.contains(document.activeElement))results.hidden=true},0)});
 field.append(input,clear);section.append(label,field,results,status,report);select(pool.find(p=>p.id==='tatum'));input.value='';clear.disabled=true;return section;
}
$('intel-search-grid').replaceChildren(createScoutSearch(1));
